### ISSUE TITLE
IP Adresse

### ISSUE THREAD

**Issue by GuenWuen** [darkiop/ioBroker.stiebel-lwz#1]
Hi,
wie verbindest du den Adapter mit der Stiebel?
Finde in dem Adapter keine Einstellungen.
Gruß

**Comment by darkiop** [comment]
Hi, an der LWZ hängt ein ISGweb und dessen IP muss in der Adapter Config eingetragen werden.

**Comment by GuenWuen** [comment]
Ich meinte eher über den Adapter im ioBroker :-)
Das ISGweb hab ich schon und funzt mit Loxone sehr gut.

**Comment by darkiop** [comment]
Dann verstehe ich die Frage nicht :) An die IP in der Adapter Config werden die Änderungen für die durch den Adapter erstellten Datenpunkte gesendet.

['ISG_SET_BETRIEBSART', 'ISG_SET_LUEFTERSTUFETAG', 'ISG_SET_RAUMTEMPTAG', 'ISG_SET_WARMWASSERTEMPTAG'];

Diese sind zur implementiert. Beitriebsart ist in Großbuchstaben einzutragen "AUTOMATIK", "WARMWASSER", ...

Bei den anderen stehen die min/max Werte in der ISGweb oder hier:

https://github.com/darkiop/ioBroker.stiebel-lwz/blob/master/isg_set.sh

Doku dazu muss ich noch anpassen bzw. die zugelassenen Werte auch validieren.

**Comment by GuenWuen** [comment]
![2018-05-24 10_54_12-iobroker admin](https://user-images.githubusercontent.com/31923191/40475104-fb58ff54-5f40-11e8-954c-fca8c8bbc6e0.png)
Ich dachte die IP wird hier eingetragen ;-)

**Comment by darkiop** [comment]
Ok, ich habe die Adapter config bisher nur für Admin3 angepasst, du hast hier noch das Standard Template.

**Comment by darkiop** [comment]
installier nochmal neu oder erstetze die 

https://github.com/darkiop/ioBroker.stiebel-lwz/blob/master/admin/index.html

manuell, sollte nun gehen.

**Comment by GuenWuen** [comment]
Hab jetzt ein Update gefahren auf admin3
![2018-05-24 17_39_03-objects - iobroker](https://user-images.githubusercontent.com/31923191/40496163-6bef668a-5f79-11e8-85f8-d1dcfe6c10aa.png)

**Comment by darkiop** [comment]
Alles klar, teile gerne deine Erfahrungen mit dem Adapter mit mir. Ist mein erster :)

**Comment by GuenWuen** [comment]
Falls ich nerve sag mir das :-)
![bildschirmfoto 2018-05-28 um 19 45 49](https://user-images.githubusercontent.com/31923191/40624956-cc7c9b6a-62af-11e8-9ba0-bd8ad35c540e.png)

**Comment by darkiop** [comment]
Passt :)
